name: Testing - main

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        include:
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.8

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-optional.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: Set Mac Paths
      if: matrix.os == 'macos-latest'
      run: |
        ls
        pwd
        for pkg in `ls /home/runner/work/pymatgen/cmd_line`; do export PATH=$PATH:/home/runner/work/pymatgen/cmd_line/$pkg/Darwin_64bit; done
        export PMG_TEST_FILES_DIR=/home/runner/work/pymatgen/test_files
        echo "PATH=$PATH"
        echo "Test files are in $PMG_TEST_FILES_DIR"
    - name: Set Windows Paths
      if: matrix.os == 'windows-latest'
      run: |
        set PMG_TEST_FILES_DIR=test_files
    - name: pytest
      env:
        PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
        MPLBACKEND: "Agg"
      run: |
        pytest pymatgen --ignore=pymatgen/analysis --color=yes
