name: Testing - main - Linux

on: [push, pull_request]

jobs:

  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install OpenBabel
      shell: bash -l {0}
      run: conda install -c conda-forge openbabel
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pwd
        ls /home/runner/work/pymatgen/pymatgen/cmd_line
        for pkg in `ls cmd_line`; do export PATH=$PATH:`pwd`/cmd_line/$pkg/Linux_64bit; done
        export GULP_LIB=/home/runner/work/pymatgen/cmd_line/gulp/Libraries
        export PMG_TEST_FILES_DIR=/home/runner/work/pymatgen/test_files
        echo "PATH=$PATH"
        echo "Test files are in $PMG_TEST_FILES_DIR"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-optional.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: pytest
      shell: bash -l {0}
      env:
        PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
        MPLBACKEND: "Agg"
      run: |
        pytest pymatgen --ignore=pymatgen/analysis --color=yes
