name: Testing - analysis - Linux

on: [push, pull_request]

jobs:

  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install OpenBabel
      shell: bash -l {0}
      run: conda install -c conda-forge openbabel

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        for pkg in `ls cmd_line`; do echo "`pwd`/cmd_line/$pkg/Linux_64bit" >> $GITHUB_PATH; done
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-optional.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: pytest
      shell: bash -l {0}
      env:
        PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
        MPLBACKEND: "Agg"
      run: |
        echo "GULP_LIB=`pwd`/cmd_line/gulp/Libraries" >> $GITHUB_ENV
        echo "PMG_TEST_FILES_DIR=`pwd`/test_files" >> $GITHUB_ENV
        echo "PATH=$PATH"
        echo "Test files are in $PMG_TEST_FILES_DIR"
        pytest pymatgen/analysis -rxXs --color=yes
